name: Create release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: FaithfulTeam/Faithful@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* *.github* .gitignore'
